print("Joshua Malapad Mendoza")
print("Lupac Boac Marinduque")
print("October 9, 2003")
print("College of Information and Computing Sciences")
print("BS in Information Technology")
print("2nd Year - B")
print("Playing Games")
print("Playing Musical Instrument")
print("Cycling")
print("Skimboarding")
print("Watching Movies")